### ISSUE TITLE
Features 3 up doesn't match current site

### ISSUE THREAD

**Issue by desbrowne** [ucare-technologies/ucarehq#49]
I'm guessing that this will need some adjustments (add some html?) to the mark down files to fix. This can be left for M5

### Gatsby 
![features 3up](https://user-images.githubusercontent.com/3364592/59681103-71576700-9216-11e9-902d-58f3e261b3c8.png)

### Current
![current features 3up](https://user-images.githubusercontent.com/3364592/59681105-71effd80-9216-11e9-9d5d-c7ee63289160.png)

**Comment by polaris218** [comment]
I have researched about this. But until yet I couldn't find the way how can I do it.
Because the markdown file doesn't include className but this is just written as <p /> tag
So if you have good way could you help me?

**Comment by desbrowne** [comment]
Leave for M5
