### ISSUE TITLE
Some of the check lists in the MD files need cleanup

### ISSUE THREAD

**Issue by desbrowne** [ucare-technologies/ucarehq#50]
The converter I created seems to have made some minor mistakes, this is a reminder for me to get these lists cleaned up.

E.g. Child safety

**Comment by polaris218** [comment]
Actually I have changed some MD file contents.
For example feature_color
At first value is hex so I couldn't read hex value with graphql
So I tried to get data and as a result I wrapped it with quotes

**Comment by polaris218** [comment]
Also youtube video is not loading as proper width and height.
I think it is depends on markdown files.
If you changed it then I can fix some css styles.

**Comment by desbrowne** [comment]
Leave for M5
